apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: itp-app
type: Opaque
stringData:
  mysql-root-password: ITPAdmin123!
  mysql-database: itpdb
  mysql-user: itpuser
  mysql-password: ITPUser123!
